export const THREAD_FILTER_OPTION_CHOSEN = 'THREAD_FILTER_OPTION_CHOSEN';
export const KIND_OF_PRODUCT_FILTER_OPTION_CHOSEN = 'KIND_OF_PRODUCT_FILTER_OPTION_CHOSEN';
export const FEATURE_FILTER_DIALOG_CLOSED = 'FEATURE_FILTER_DIALOG_CLOSED';
export const FEATURE_FILTER_DIALOG_OPENED = 'FEATURE_FILTER_DIALOG_OPENED';
export const FEATURE_FILTER_OPTION_CHOSEN = 'FEATURE_FILTER_OPTION_CHOSEN';
export const FEATURE_FILTER_OPTION_DESELECTED = 'FEATURE_FILTER_OPTION_DESELECTED';