export const THREAD_FILTER_OPTION_CHOSEN = 'THREAD_FILTER_OPTION_CHOSEN';
export const KIND_OF_PRODUCT_FILTER_OPTION_CHOSEN = 'KIND_OF_PRODUCT_FILTER_OPTION_CHOSEN';
export const FEATURE_FILTER_DIALOG_CLOSED = 'FEATURE_FILTER_DIALOG_CLOSED';
export const FEATURE_FILTER_DIALOG_OPENED = 'FEATURE_FILTER_DIALOG_OPENED';
export const FEATURE_FILTER_OPTION_CHOSEN = 'FEATURE_FILTER_OPTION_CHOSEN';
export const FEATURE_FILTER_OPTION_DESELECTED = 'FEATURE_FILTER_OPTION_DESELECTED';
export const MEASUREMENT_FILTER_DIALOG_OPENED = 'MEASUREMENT_FILTER_DIALOG_OPENED';
export const MEASUREMENT_FILTER_DIALOG_CLOSED = 'MEASUREMENT_FILTER_DIALOG_CLOSED';
export const MEASUREMENT_FILTER_OPTION_CHOSEN = 'MEASUREMENT_FILTER_OPTION_CHOSEN';
export const MEASUREMENT_FILTER_OPTION_DESELECTED = 'MEASUREMENT_FILTER_OPTION_DESELECTED';

export const LOADING_PRODUCT_RECORDS = 'LOADING_PRODUCT_RECORDS';
export const SUCCESS_LOADING_PRODUCTS = 'SUCCESS_LOADING_PRODUCTS';
export const FAILED_LOADING_PRODUCTS = 'FAILED_LOADING_PRODUCTS';