export const ADD_TO_PRE_SALE = 'ADD_TO_PRE_SALE';
export const REMOVE_FROM_PRE_SALE = 'REMOVE_FROM_PRE_SALE';

export const ADD_TO_SHOPPING_LIST = 'ADD_TO_SHOPPING_LIST';
export const REMOVE_FROM_SHOPPING_LIST = 'REMOVE_FROM_SHOPPING_LIST';